eureka:
  client:
    service-url:
      defaultZone: http://finder:9001/eureka
#    register-with-eureka: false

#spring:
#  zipkin:
#    base-url: http://trail:9002
#    sender:
#      type: web
#
#  sleuth:
#    sampler:
#      probability: 1.0