eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
#    register-with-eureka: false
spring:
  zipkin:
    base-url: http://localhost:9002
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0