spring:
  application:
    name: zone
  profiles:
    active: local
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  zipkin:
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9010
  tomcat:
    uri-encoding: UTF-8